#--------------------------------------------------
# Copyright (c) 2026 SECOM CO., LTD. All Rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#--------------------------------------------------

#
# Test targets for attester
#

ROOT_DIR ?= $(CURDIR)
SGX_SDK ?= /opt/intel/sgxsdk

BUILD_DIR := $(ROOT_DIR)/build

TEST_COMMON_INCLUDES := \
	-IEnclave/inc \
	-I$(ROOT_DIR)/common \
	-I$(ROOT_DIR)/third_party/t_cose/inc \
	-I$(ROOT_DIR)/third_party/QCBOR/inc \
	-I$(ROOT_DIR)/third_party/libcsuit/inc \
	-I$(ROOT_DIR)/third_party/libteep/inc

TEST_COMMON_LIB_DIRS := -L$(ROOT_DIR)/lib
TEST_COMMON_LIBS := -lcsuit -lteep -lt_cose -lqcbor -lcrypto
SUIT_CALLBACK_WRAP_FLAGS := \
	-Wl,--wrap=suit_store_callback \
	-Wl,--wrap=suit_condition_callback \
	-Wl,--wrap=suit_report_callback

MANIFEST_RECORD_TEST_BIN := $(BUILD_DIR)/manifest_record_store_test
SUIT_CONDITION_CALLBACK_TEST_BIN := $(BUILD_DIR)/suit_condition_callback_test
ENCLAVE_WASM_INVOKE_TEST_BIN := $(BUILD_DIR)/enclave_wasm_invoke_test
TC_UPDATE_INTEGRATION_TEST_BIN := $(BUILD_DIR)/tc_update_integration_test
TC_MANAGER_GET_TC_LIST_TEST_BIN := $(BUILD_DIR)/tc_manager_get_tc_list_test

.PHONY: all manifest-record-store-test suit-condition-callback-test enclave-wasm-invoke-test tc-update-integration-test tc-manager-get-tc-list-test clean run


all: $(MANIFEST_RECORD_TEST_BIN) $(SUIT_CONDITION_CALLBACK_TEST_BIN) $(ENCLAVE_WASM_INVOKE_TEST_BIN) $(TC_UPDATE_INTEGRATION_TEST_BIN) $(TC_MANAGER_GET_TC_LIST_TEST_BIN)

clean:
	$(RM) $(MANIFEST_RECORD_TEST_BIN) $(SUIT_CONDITION_CALLBACK_TEST_BIN) $(ENCLAVE_WASM_INVOKE_TEST_BIN) $(TC_UPDATE_INTEGRATION_TEST_BIN) $(TC_MANAGER_GET_TC_LIST_TEST_BIN)

run: manifest-record-store-test suit-condition-callback-test enclave-wasm-invoke-test tc-update-integration-test tc-manager-get-tc-list-test



MANIFEST_RECORD_TEST_SRCS := Enclave/tests/manifest_record_store_test.cpp Enclave/src/tc_manager.cpp

manifest-record-store-test: $(MANIFEST_RECORD_TEST_BIN)
	$(MANIFEST_RECORD_TEST_BIN)

$(MANIFEST_RECORD_TEST_BIN): $(MANIFEST_RECORD_TEST_SRCS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) -std=c++11 -g $(TEST_COMMON_INCLUDES) $^ $(TEST_COMMON_LIB_DIRS) $(TEST_COMMON_LIBS) -o $@
	@echo "CXX  =>  $@"


SUIT_CONDITION_CALLBACK_TEST_SRCS := Enclave/tests/suit_condition_callback_test.cpp \
	Enclave/tests/test_helpers.cpp \
	Enclave/src/suit_processor_wrapper.cpp \
	Enclave/src/tc_manager.cpp

suit-condition-callback-test: $(SUIT_CONDITION_CALLBACK_TEST_BIN)
	$(SUIT_CONDITION_CALLBACK_TEST_BIN)

$(SUIT_CONDITION_CALLBACK_TEST_BIN): $(SUIT_CONDITION_CALLBACK_TEST_SRCS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) -std=c++11 -g $(TEST_COMMON_INCLUDES) $^ $(TEST_COMMON_LIB_DIRS) $(TEST_COMMON_LIBS) \
		$(SUIT_CALLBACK_WRAP_FLAGS) \
		-o $@
	@echo "CXX  =>  $@"


ENCLAVE_WASM_INVOKE_TEST_SRCS := Enclave/tests/enclave_wasm_invoke_test.cpp \
	Enclave/src/Enclave_wasm.cpp

enclave-wasm-invoke-test: $(ENCLAVE_WASM_INVOKE_TEST_BIN)
	$(ENCLAVE_WASM_INVOKE_TEST_BIN)

$(ENCLAVE_WASM_INVOKE_TEST_BIN): $(ENCLAVE_WASM_INVOKE_TEST_SRCS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) -std=c++11 -g \
		$(TEST_COMMON_INCLUDES) \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/iwasm/include \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/shared/utils \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/shared/platform/include \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/shared/platform/linux-sgx \
		-I$(SGX_SDK)/include \
		$^ $(TEST_COMMON_LIB_DIRS) -lcsuit -lt_cose -lqcbor -lcrypto -o $@
	@echo "CXX  =>  $@"


TC_UPDATE_INTEGRATION_TEST_SRCS := Enclave/tests/tc_update_integration_test.cpp \
	Enclave/src/suit_processor_wrapper.cpp \
	Enclave/src/tc_manager.cpp

tc-update-integration-test: $(TC_UPDATE_INTEGRATION_TEST_BIN)
	$(TC_UPDATE_INTEGRATION_TEST_BIN)

$(TC_UPDATE_INTEGRATION_TEST_BIN): $(TC_UPDATE_INTEGRATION_TEST_SRCS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) -std=c++11 -g $(TEST_COMMON_INCLUDES) $^ $(TEST_COMMON_LIB_DIRS) $(TEST_COMMON_LIBS) \
		$(SUIT_CALLBACK_WRAP_FLAGS) \
		-o $@
	@echo "CXX  =>  $@"


TC_MANAGER_GET_TC_LIST_TEST_SRCS := Enclave/tests/tc_manager_get_tc_list_test.cpp \
	Enclave/tests/test_helpers.cpp \
	Enclave/src/tc_manager.cpp

tc-manager-get-tc-list-test: $(TC_MANAGER_GET_TC_LIST_TEST_BIN)
	$(TC_MANAGER_GET_TC_LIST_TEST_BIN)

$(TC_MANAGER_GET_TC_LIST_TEST_BIN): $(TC_MANAGER_GET_TC_LIST_TEST_SRCS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) -std=c++11 -g $(TEST_COMMON_INCLUDES) $^ $(TEST_COMMON_LIB_DIRS) $(TEST_COMMON_LIBS) -o $@
	@echo "CXX  =>  $@"

include Makefile.sgx.test
