#--------------------------------------------------
# Copyright (c) 2026 SECOM CO., LTD. All Rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#--------------------------------------------------

#
# Test targets for attester
#

ROOT_DIR ?= $(CURDIR)
SGX_SDK ?= /opt/intel/sgxsdk
SGX_MODE ?= HW
SGX_ARCH ?= x64
SGX_DEBUG ?= 1

ifeq ($(shell getconf LONG_BIT), 32)
    SGX_ARCH := x86
else ifeq ($(findstring -m32, $(CXXFLAGS)), -m32)
    SGX_ARCH := x86
endif

ifeq ($(SGX_ARCH), x86)
    SGX_COMMON_FLAGS := -m32
    SGX_LIBRARY_PATH := $(SGX_SDK)/lib
    SGX_ENCLAVE_SIGNER := $(SGX_SDK)/bin/x86/sgx_sign
    SGX_EDGER8R := $(SGX_SDK)/bin/x86/sgx_edger8r
else
    SGX_COMMON_FLAGS := -m64
    SGX_LIBRARY_PATH := $(SGX_SDK)/lib64
    SGX_ENCLAVE_SIGNER := $(SGX_SDK)/bin/x64/sgx_sign
    SGX_EDGER8R := $(SGX_SDK)/bin/x64/sgx_edger8r
endif

ifeq ($(SGX_DEBUG), 1)
    SGX_COMMON_FLAGS += -O0 -g -DDEBUG
else
    SGX_COMMON_FLAGS += -O2
endif

SGX_COMMON_FLAGS += -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type \
                    -Waddress -Wsequence-point -Wformat-security \
                    -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow \
                    -Wcast-align -Wcast-qual -Wconversion -Wredundant-decls
SGX_COMMON_CFLAGS := $(SGX_COMMON_FLAGS) -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants
SGX_COMMON_CXXFLAGS := $(SGX_COMMON_FLAGS) -Wnon-virtual-dtor -std=c++11

ifneq ($(SGX_MODE), HW)
    Urts_Library_Name := sgx_urts_sim
    Uae_Service_Library_Name := sgx_uae_service_sim
    Trts_Library_Name := sgx_trts_sim
    Service_Library_Name := sgx_tservice_sim
else
    Urts_Library_Name := sgx_urts
    Uae_Service_Library_Name := sgx_uae_service
    Trts_Library_Name := sgx_trts
    Service_Library_Name := sgx_tservice
endif

MANIFEST_RECORD_TEST_BIN := $(ROOT_DIR)/build/manifest_record_store_test
SUIT_CONDITION_CALLBACK_TEST_BIN := $(ROOT_DIR)/build/suit_condition_callback_test
ENCLAVE_WASM_INVOKE_TEST_BIN := $(ROOT_DIR)/build/enclave_wasm_invoke_test
TC_UPDATE_INTEGRATION_TEST_BIN := $(ROOT_DIR)/build/tc_update_integration_test
TC_MANAGER_GET_TC_LIST_TEST_BIN := $(ROOT_DIR)/build/tc_manager_get_tc_list_test
PROCESS_QUERY_REQUEST_TEST_BIN := $(ROOT_DIR)/build/proces_query_request_test
DCAP_QUOTE_OCALLS_TEST_BIN := $(ROOT_DIR)/build/dcap_quote_ocalls_test

.PHONY: all manifest-record-store-test suit-condition-callback-test enclave-wasm-invoke-test tc-update-integration-test tc-manager-get-tc-list-test process-query-request-test dcap-quote-ocalls-test clean run


all: $(MANIFEST_RECORD_TEST_BIN) $(SUIT_CONDITION_CALLBACK_TEST_BIN) $(ENCLAVE_WASM_INVOKE_TEST_BIN) $(TC_UPDATE_INTEGRATION_TEST_BIN) $(TC_MANAGER_GET_TC_LIST_TEST_BIN) $(PROCESS_QUERY_REQUEST_TEST_BIN)

clean:
	$(RM) $(MANIFEST_RECORD_TEST_BIN) $(SUIT_CONDITION_CALLBACK_TEST_BIN) $(ENCLAVE_WASM_INVOKE_TEST_BIN) $(TC_UPDATE_INTEGRATION_TEST_BIN) $(TC_MANAGER_GET_TC_LIST_TEST_BIN) $(PROCESS_QUERY_REQUEST_TEST_BIN) $(DCAP_QUOTE_OCALLS_TEST_BIN)
	$(RM) -r $(ROOT_DIR)/build/create_evidence_dcap_integration

run: manifest-record-store-test suit-condition-callback-test enclave-wasm-invoke-test tc-update-integration-test tc-manager-get-tc-list-test process-query-request-test



MANIFEST_RECORD_TEST_SRCS := Enclave/tests/manifest_record_store_test.cpp Enclave/src/tc_manager.cpp

manifest-record-store-test: $(MANIFEST_RECORD_TEST_BIN)
	$(MANIFEST_RECORD_TEST_BIN)

$(MANIFEST_RECORD_TEST_BIN): $(MANIFEST_RECORD_TEST_SRCS)
	@mkdir -p $(ROOT_DIR)/build
	$(CXX) -std=c++11 -g -IEnclave/inc -I$(ROOT_DIR)/common -I$(ROOT_DIR)/third_party/t_cose/inc -I$(ROOT_DIR)/third_party/QCBOR/inc -I$(ROOT_DIR)/third_party/libcsuit/inc -I$(ROOT_DIR)/third_party/libteep/inc $^ -L$(ROOT_DIR)/lib -lcsuit -lteep -lt_cose -lqcbor -lcrypto -o $@
	@echo "CXX  =>  $@"


SUIT_CONDITION_CALLBACK_TEST_SRCS := Enclave/tests/suit_condition_callback_test.cpp \
	Enclave/tests/test_helpers.cpp \
	Enclave/src/suit_processor_wrapper.cpp \
	Enclave/src/tc_manager.cpp

suit-condition-callback-test: $(SUIT_CONDITION_CALLBACK_TEST_BIN)
	$(SUIT_CONDITION_CALLBACK_TEST_BIN)

$(SUIT_CONDITION_CALLBACK_TEST_BIN): $(SUIT_CONDITION_CALLBACK_TEST_SRCS)
	@mkdir -p $(ROOT_DIR)/build
	$(CXX) -std=c++11 -g -IEnclave/inc -I$(ROOT_DIR)/common -I$(ROOT_DIR)/third_party/t_cose/inc -I$(ROOT_DIR)/third_party/QCBOR/inc -I$(ROOT_DIR)/third_party/libcsuit/inc -I$(ROOT_DIR)/third_party/libteep/inc $^ -L$(ROOT_DIR)/lib -lcsuit -lteep -lt_cose -lqcbor -lcrypto \
		-Wl,--wrap=suit_store_callback -Wl,--wrap=suit_condition_callback -Wl,--wrap=suit_report_callback \
		-o $@
	@echo "CXX  =>  $@"


ENCLAVE_WASM_INVOKE_TEST_SRCS := Enclave/tests/enclave_wasm_invoke_test.cpp \
	Enclave/src/Enclave_wasm.cpp

enclave-wasm-invoke-test: $(ENCLAVE_WASM_INVOKE_TEST_BIN)
	$(ENCLAVE_WASM_INVOKE_TEST_BIN)

$(ENCLAVE_WASM_INVOKE_TEST_BIN): $(ENCLAVE_WASM_INVOKE_TEST_SRCS)
	@mkdir -p $(ROOT_DIR)/build
	$(CXX) -std=c++11 -g \
		-IEnclave/inc \
		-I$(ROOT_DIR)/common \
		-I$(ROOT_DIR)/third_party/t_cose/inc \
		-I$(ROOT_DIR)/third_party/QCBOR/inc \
		-I$(ROOT_DIR)/third_party/libcsuit/inc \
		-I$(ROOT_DIR)/third_party/libteep/inc \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/iwasm/include \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/shared/utils \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/shared/platform/include \
		-I$(ROOT_DIR)/third_party/wasm-micro-runtime/core/shared/platform/linux-sgx \
		-I$(SGX_SDK)/include \
		$^ -L$(ROOT_DIR)/lib -lcsuit -lt_cose -lqcbor -lcrypto -o $@
	@echo "CXX  =>  $@"


TC_UPDATE_INTEGRATION_TEST_SRCS := Enclave/tests/tc_update_integration_test.cpp \
	Enclave/src/suit_processor_wrapper.cpp \
	Enclave/src/tc_manager.cpp

tc-update-integration-test: $(TC_UPDATE_INTEGRATION_TEST_BIN)
	$(TC_UPDATE_INTEGRATION_TEST_BIN)

$(TC_UPDATE_INTEGRATION_TEST_BIN): $(TC_UPDATE_INTEGRATION_TEST_SRCS)
	@mkdir -p $(ROOT_DIR)/build
	$(CXX) -std=c++11 -g -IEnclave/inc -I$(ROOT_DIR)/common -I$(ROOT_DIR)/third_party/t_cose/inc -I$(ROOT_DIR)/third_party/QCBOR/inc -I$(ROOT_DIR)/third_party/libcsuit/inc -I$(ROOT_DIR)/third_party/libteep/inc $^ -L$(ROOT_DIR)/lib -lcsuit -lteep -lt_cose -lqcbor -lcrypto \
		-Wl,--wrap=suit_store_callback -Wl,--wrap=suit_condition_callback -Wl,--wrap=suit_report_callback \
		-o $@
	@echo "CXX  =>  $@"


TC_MANAGER_GET_TC_LIST_TEST_SRCS := Enclave/tests/tc_manager_get_tc_list_test.cpp \
	Enclave/tests/test_helpers.cpp \
	Enclave/src/tc_manager.cpp

tc-manager-get-tc-list-test: $(TC_MANAGER_GET_TC_LIST_TEST_BIN)
	$(TC_MANAGER_GET_TC_LIST_TEST_BIN)

$(TC_MANAGER_GET_TC_LIST_TEST_BIN): $(TC_MANAGER_GET_TC_LIST_TEST_SRCS)
	@mkdir -p $(ROOT_DIR)/build
	$(CXX) -std=c++11 -g -IEnclave/inc -I$(ROOT_DIR)/common -I$(ROOT_DIR)/third_party/t_cose/inc -I$(ROOT_DIR)/third_party/QCBOR/inc -I$(ROOT_DIR)/third_party/libcsuit/inc -I$(ROOT_DIR)/third_party/libteep/inc $^ -L$(ROOT_DIR)/lib -lcsuit -lteep -lt_cose -lqcbor -lcrypto -o $@
	@echo "CXX  =>  $@"


PROCESS_QUERY_REQUEST_TEST_SRCS := Enclave/tests/proces_query_request_test.cpp \
	Enclave/tests/test_helpers.cpp \
	Enclave/src/Enclave_process_message.cpp \
	Enclave/src/suit_processor_wrapper.cpp \
	Enclave/src/tc_manager.cpp

process-query-request-test: $(PROCESS_QUERY_REQUEST_TEST_BIN)
	$(PROCESS_QUERY_REQUEST_TEST_BIN)

$(PROCESS_QUERY_REQUEST_TEST_BIN): $(PROCESS_QUERY_REQUEST_TEST_SRCS)
	@mkdir -p $(ROOT_DIR)/build
	$(CXX) -std=c++11 -g -IEnclave/inc -I$(ROOT_DIR)/common -I$(ROOT_DIR)/third_party/t_cose/inc -I$(ROOT_DIR)/third_party/QCBOR/inc -I$(ROOT_DIR)/third_party/libcsuit/inc -I$(ROOT_DIR)/third_party/libteep/inc $^ -L$(ROOT_DIR)/lib -lcsuit -lteep -lt_cose -lqcbor -lcrypto \
		-Wl,--wrap=suit_store_callback -Wl,--wrap=suit_condition_callback -Wl,--wrap=suit_report_callback \
		-o $@
	@echo "CXX  =>  $@"


DCAP_QUOTE_OCALLS_TEST_SRCS := App/tests/dcap_quote_ocalls_test.cpp \
	App/src/dcap_quote_ocalls.cpp

dcap-quote-ocalls-test: $(DCAP_QUOTE_OCALLS_TEST_BIN)
	$(DCAP_QUOTE_OCALLS_TEST_BIN)

$(DCAP_QUOTE_OCALLS_TEST_BIN): $(DCAP_QUOTE_OCALLS_TEST_SRCS)
	@mkdir -p $(ROOT_DIR)/build
	$(CXX) -std=c++11 -g -IApp/inc -I$(SGX_SDK)/include $^ -lsgx_dcap_ql -o $@
	@echo "CXX  =>  $@"


.PHONY: create-evidence-dcap-integration-test

CREATE_EVIDENCE_DCAP_INTEGRATION_DIR := $(ROOT_DIR)/build/create_evidence_dcap_integration
CREATE_EVIDENCE_DCAP_INTEGRATION_EDL := Enclave/tests/create_evidence_dcap_integration.edl
CREATE_EVIDENCE_DCAP_INTEGRATION_U_C := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_u.c
CREATE_EVIDENCE_DCAP_INTEGRATION_U_H := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_u.h
CREATE_EVIDENCE_DCAP_INTEGRATION_T_C := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_t.c
CREATE_EVIDENCE_DCAP_INTEGRATION_T_H := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_t.h
CREATE_EVIDENCE_DCAP_INTEGRATION_U_O := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_u.o
CREATE_EVIDENCE_DCAP_INTEGRATION_T_O := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_t.o
CREATE_EVIDENCE_DCAP_INTEGRATION_HOST_O := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_test.o
CREATE_EVIDENCE_DCAP_INTEGRATION_OCALL_O := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/dcap_quote_ocalls.o
CREATE_EVIDENCE_DCAP_INTEGRATION_ECALL_O := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_ecall.o
CREATE_EVIDENCE_DCAP_INTEGRATION_EVIDENCE_O := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/Enclave_generate_evidence.o
CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_enclave.so
CREATE_EVIDENCE_DCAP_INTEGRATION_SIGNED_ENCLAVE := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_enclave.signed.so
CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_BIN := $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)/create_evidence_dcap_integration_test
CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_KEY := Enclave/Enclave_private_test.pem
CREATE_EVIDENCE_DCAP_INTEGRATION_CONFIG := Enclave/Enclave.config.xml

CREATE_EVIDENCE_DCAP_INTEGRATION_SYS_INC := \
	-isystem $(ROOT_DIR)/third_party/QCBOR/inc \
	-isystem $(ROOT_DIR)/third_party/t_cose/inc \
	-isystem $(ROOT_DIR)/third_party/libteep/inc \
	-isystem $(ROOT_DIR)/third_party/libcsuit/inc \
	-isystem $(ROOT_DIR)/third_party/intel-sgx-ssl/Linux/package/include

CREATE_EVIDENCE_DCAP_INTEGRATION_APP_INC := \
	-I$(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR) \
	-IApp/inc \
	-I$(SGX_SDK)/include \
	$(CREATE_EVIDENCE_DCAP_INTEGRATION_SYS_INC)

CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_INC := \
	-I$(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR) \
	-IEnclave \
	-IEnclave/inc \
	-Icommon \
	-I$(SGX_SDK)/include \
	-I$(SGX_SDK)/include/libcxx \
	-I$(SGX_SDK)/include/tlibc \
	$(CREATE_EVIDENCE_DCAP_INTEGRATION_SYS_INC)

CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_C_FLAGS := \
	-nostdinc -fvisibility=hidden -fpie -fstack-protector -fno-builtin-printf \
	-ffunction-sections -fdata-sections \
	$(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_INC)

CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_CXX_FLAGS := \
	$(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_C_FLAGS) -nostdinc++

CREATE_EVIDENCE_DCAP_INTEGRATION_LINK_FLAGS := \
	-Wl,-z,relro,-z,now,-z,noexecstack -Wl,--gc-sections \
	-Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles \
	-L$(SGX_LIBRARY_PATH) -L$(ROOT_DIR)/lib \
	-Wl,--whole-archive -l$(Trts_Library_Name) -Wl,--no-whole-archive \
	-Wl,--start-group -lsgx_tstdc -lsgx_tcxx -lsgx_tcrypto -l$(Service_Library_Name) -Wl,--end-group \
	-Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined \
	-Wl,-pie,-eenclave_entry -Wl,--export-dynamic \
	-Wl,--defsym,__ImageBase=0 \
	-Wl,--version-script=Enclave/Enclave_debug.lds

create-evidence-dcap-integration-test: $(CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_BIN) $(CREATE_EVIDENCE_DCAP_INTEGRATION_SIGNED_ENCLAVE)
	REQUIRE_DCAP=$(REQUIRE_DCAP) $(CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_BIN)

$(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR):
	@mkdir -p $@

$(CREATE_EVIDENCE_DCAP_INTEGRATION_U_H) $(CREATE_EVIDENCE_DCAP_INTEGRATION_U_C): $(CREATE_EVIDENCE_DCAP_INTEGRATION_EDL) | $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)
	@cd $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR) && $(SGX_EDGER8R) --untrusted $(ROOT_DIR)/$(CREATE_EVIDENCE_DCAP_INTEGRATION_EDL) --search-path $(ROOT_DIR)/Enclave/tests --search-path $(ROOT_DIR)/common --search-path $(SGX_SDK)/include
	@echo "GEN  =>  $(CREATE_EVIDENCE_DCAP_INTEGRATION_U_H)"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_T_H) $(CREATE_EVIDENCE_DCAP_INTEGRATION_T_C): $(CREATE_EVIDENCE_DCAP_INTEGRATION_EDL) | $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR)
	@cd $(CREATE_EVIDENCE_DCAP_INTEGRATION_DIR) && $(SGX_EDGER8R) --trusted $(ROOT_DIR)/$(CREATE_EVIDENCE_DCAP_INTEGRATION_EDL) --search-path $(ROOT_DIR)/Enclave/tests --search-path $(ROOT_DIR)/common --search-path $(SGX_SDK)/include
	@echo "GEN  =>  $(CREATE_EVIDENCE_DCAP_INTEGRATION_T_H)"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_U_O): $(CREATE_EVIDENCE_DCAP_INTEGRATION_U_C) $(CREATE_EVIDENCE_DCAP_INTEGRATION_U_H)
	$(CC) $(SGX_COMMON_CFLAGS) -fPIC -Wno-attributes $(CREATE_EVIDENCE_DCAP_INTEGRATION_APP_INC) -c $< -o $@
	@echo "CC   <=  $<"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_HOST_O): App/tests/create_evidence_dcap_integration_test.cpp $(CREATE_EVIDENCE_DCAP_INTEGRATION_U_H)
	$(CXX) $(SGX_COMMON_CXXFLAGS) -fPIC -Wno-attributes $(CREATE_EVIDENCE_DCAP_INTEGRATION_APP_INC) -DTEST_ENCLAVE_FILENAME=\"$(CREATE_EVIDENCE_DCAP_INTEGRATION_SIGNED_ENCLAVE)\" -c $< -o $@
	@echo "CXX  <=  $<"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_OCALL_O): App/src/dcap_quote_ocalls.cpp App/inc/dcap_quote_ocalls.h
	$(CXX) $(SGX_COMMON_CXXFLAGS) -fPIC -Wno-attributes $(CREATE_EVIDENCE_DCAP_INTEGRATION_APP_INC) -c $< -o $@
	@echo "CXX  <=  $<"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_BIN): $(CREATE_EVIDENCE_DCAP_INTEGRATION_HOST_O) $(CREATE_EVIDENCE_DCAP_INTEGRATION_U_O) $(CREATE_EVIDENCE_DCAP_INTEGRATION_OCALL_O)
	$(CXX) $^ -o $@ -L$(SGX_LIBRARY_PATH) -l$(Urts_Library_Name) -l$(Uae_Service_Library_Name) -lsgx_dcap_ql -lpthread
	@echo "LINK =>  $@"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_T_O): $(CREATE_EVIDENCE_DCAP_INTEGRATION_T_C) $(CREATE_EVIDENCE_DCAP_INTEGRATION_T_H)
	$(CC) $(SGX_COMMON_CFLAGS) $(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_C_FLAGS) -c $< -o $@
	@echo "CC   <=  $<"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_ECALL_O): Enclave/tests/create_evidence_dcap_integration_ecall.cpp $(CREATE_EVIDENCE_DCAP_INTEGRATION_T_H)
	$(CXX) $(SGX_COMMON_CXXFLAGS) $(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_CXX_FLAGS) -c $< -o $@
	@echo "CXX  <=  $<"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_EVIDENCE_O): Enclave/src/Enclave_generate_evidence.cpp $(CREATE_EVIDENCE_DCAP_INTEGRATION_T_H)
	$(CXX) $(SGX_COMMON_CXXFLAGS) $(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE_CXX_FLAGS) -c $< -o $@
	@echo "CXX  <=  $<"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE): $(CREATE_EVIDENCE_DCAP_INTEGRATION_T_O) $(CREATE_EVIDENCE_DCAP_INTEGRATION_ECALL_O) $(CREATE_EVIDENCE_DCAP_INTEGRATION_EVIDENCE_O)
	$(CXX) $^ -o $@ $(CREATE_EVIDENCE_DCAP_INTEGRATION_LINK_FLAGS)
	@echo "LINK =>  $@"

$(CREATE_EVIDENCE_DCAP_INTEGRATION_SIGNED_ENCLAVE): $(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE)
ifeq ($(wildcard $(CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_KEY)),)
	@openssl genrsa -out $(CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_KEY) -3 3072
endif
	@$(SGX_ENCLAVE_SIGNER) sign -key $(CREATE_EVIDENCE_DCAP_INTEGRATION_TEST_KEY) -enclave $(CREATE_EVIDENCE_DCAP_INTEGRATION_ENCLAVE) -out $@ -config $(CREATE_EVIDENCE_DCAP_INTEGRATION_CONFIG)
	@echo "SIGN =>  $@"
