/*
 * Copyright (c) 2026 SECOM CO., LTD. All Rights reserved.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#ifndef SUIT_CONDITION_CALLBACK_H_
#define SUIT_CONDITION_CALLBACK_H_


#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
#define delete delete_perm
extern "C" {
#endif
#include "csuit/suit_common.h"
#include "csuit/suit_manifest_process.h"
#ifdef __cplusplus
}
#undef delete
#endif


#ifdef __cplusplus
extern "C" {
#endif

/*!
    \brief      Wrapped store callback to store Trusted Component.

    \param[in]  store_args  SUIT store callback arguments.
    \return     SUIT_SUCCESS on success or an error code.
*/
suit_err_t __wrap_suit_store_callback(suit_store_args_t store_args);

/*!
    \brief      Wrapped invoke callback to suppress default libcsuit logging.

    \param[in]  invoke_args  SUIT invoke callback arguments.
    \return     SUIT_SUCCESS on success or an error code.
*/
suit_err_t __wrap_suit_invoke_callback(suit_invoke_args_t invoke_args);

/*!
    \brief      Wrapped condition callback to enforce hash match checks.

    \param[in]  condition_args  SUIT condition callback arguments.
    \param[out] condition_ret   Result details for reporting engine.
    \return     SUIT_SUCCESS on success or an error code.
*/
suit_err_t __wrap_suit_condition_callback(suit_condition_args_t condition_args,
                                          suit_callback_ret_t *condition_ret);

/*!
    \brief      Wrapped report callback to retain the report buffer.

    \param[in]  report_args  SUIT report callback arguments.
    \return     SUIT_SUCCESS on success or an error code.
*/
suit_err_t __wrap_suit_report_callback(suit_report_args_t report_args);

/*!
    \brief      Get the SUIT report generated by libcsuit.

    \param[out] len  Length of the report buffer.
    \return     Pointer to the report buffer, or NULL if none.
*/
const uint8_t *suit_get_suit_report(size_t *len);

#ifdef __cplusplus
}
#endif



#endif  /* SUIT_CONDITION_CALLBACK_H_ */
