#ifndef TEEP_BUFFER_SIZES_H
#define TEEP_BUFFER_SIZES_H

#define TEEP_MESSAGE_BUFFER_SIZE (1024 * 64)
#define TEEP_SEND_BUFFER_SIZE TEEP_MESSAGE_BUFFER_SIZE
#define TEEP_WORK_BUFFER_SIZE TEEP_MESSAGE_BUFFER_SIZE

#endif /* TEEP_BUFFER_SIZES_H */
